db:
  name: postgres
  address: ${Server.postgres.host}
  port: ${Server.postgres.port}
  username: ${Server.postgres.login}
  password: ${Server.postgres.password}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  datasource:
    url: 'jdbc:postgresql://${db.address}:${db.port}/${db.name}'
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  application:
    name: "web"

datasource:
  multiply:
    - dbName: postgres
      address: ${Server.postgres.host}
      port: ${Server.postgres.port}
      username: ${Server.postgres.login}
      password: ${Server.postgres.password}
      persistenceUnitName: postgresPU
      packagePath: ru.mirea.sdk.entity
      dbType: postgresql
      driver-class-name: org.postgresql.Driver
    - dbName: test
      address: ${Server.postgres.host}
      port: ${Server.postgres.port}
      username: ${Server.postgres.login}
      password: ${Server.postgres.password}
      persistenceUnitName: testPU
      packagePath: ru.mirea.sdk.entity
      dbType: postgresql
      driver-class-name: org.postgresql.Driver
    - dbName: test_2
      address: ${Server.postgres.host}
      port: ${Server.postgres.port}
      username: ${Server.postgres.login}
      password: ${Server.postgres.password}
      persistenceUnitName: test2PU
      packagePath: ru.mirea.sdk.entity
      dbType: postgresql
      driver-class-name: org.postgresql.Driver

